create schema if not exists private;

create table if not exists public.lavtudo_washes (
  id bigint generated by default as identity (start with 1025) primary key,
  customer_name text not null check (char_length(customer_name) between 1 and 120),
  machine_label text not null check (char_length(machine_label) between 1 and 80),
  service_type text not null check (service_type in ('wash', 'wash-dry')),
  status text not null default 'waiting' check (
    status in ('waiting', 'washing', 'rinsing', 'spinning', 'drying', 'ready', 'collected', 'cancelled')
  ),
  estimated_minutes integer not null check (estimated_minutes between 1 and 240),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  started_at timestamptz,
  ready_at timestamptz
);

create table if not exists public.lavtudo_wash_history (
  id bigint generated always as identity primary key,
  wash_id bigint not null references public.lavtudo_washes(id) on delete cascade,
  status text not null check (
    status in ('waiting', 'washing', 'rinsing', 'spinning', 'drying', 'ready', 'collected', 'cancelled')
  ),
  label text not null,
  occurred_at timestamptz not null default now(),
  actor text not null check (actor in ('system', 'employee'))
);

create index if not exists lavtudo_washes_updated_at_idx
  on public.lavtudo_washes (updated_at desc);
create index if not exists lavtudo_wash_history_wash_id_occurred_at_idx
  on public.lavtudo_wash_history (wash_id, occurred_at, id);

alter table public.lavtudo_washes enable row level security;
alter table public.lavtudo_washes force row level security;
alter table public.lavtudo_wash_history enable row level security;
alter table public.lavtudo_wash_history force row level security;

revoke all on table public.lavtudo_washes from public, anon, authenticated;
revoke all on table public.lavtudo_wash_history from public, anon, authenticated;
revoke all on sequence public.lavtudo_washes_id_seq from public, anon, authenticated;
revoke all on sequence public.lavtudo_wash_history_id_seq from public, anon, authenticated;

create or replace function private.lavtudo_admin_ok(p_user text, p_password text)
returns boolean
language sql
immutable
security invoker
set search_path = ''
as $$
  select p_user = 'admin' and p_password = 'admin';
$$;

create or replace function private.lavtudo_status_label(p_status text)
returns text
language sql
immutable
security invoker
set search_path = ''
as $$
  select case p_status
    when 'waiting' then 'Aguardando início'
    when 'washing' then 'Lavagem em andamento'
    when 'rinsing' then 'Enxágue em andamento'
    when 'spinning' then 'Centrifugação em andamento'
    when 'drying' then 'Secagem em andamento'
    when 'ready' then 'Pronta para retirada'
    when 'collected' then 'Roupa retirada'
    when 'cancelled' then 'Lavagem cancelada'
  end;
$$;

create or replace function private.lavtudo_wash_json(p_id bigint)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select jsonb_build_object(
    'id', wash.id::text,
    'customerName', wash.customer_name,
    'machineLabel', wash.machine_label,
    'serviceType', wash.service_type,
    'status', wash.status,
    'estimatedMinutes', wash.estimated_minutes,
    'createdAt', wash.created_at,
    'updatedAt', wash.updated_at,
    'startedAt', wash.started_at,
    'readyAt', wash.ready_at,
    'history', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', history.id::text,
          'status', history.status,
          'label', history.label,
          'at', history.occurred_at,
          'actor', history.actor
        ) order by history.occurred_at, history.id
      )
      from public.lavtudo_wash_history as history
      where history.wash_id = wash.id
    ), '[]'::jsonb)
  )
  from public.lavtudo_washes as wash
  where wash.id = p_id;
$$;

create or replace function public.lavtudo_get_wash(p_id text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  numeric_id bigint;
begin
  if p_id !~ '^[0-9]{1,12}$' then
    return null;
  end if;
  numeric_id := p_id::bigint;
  return private.lavtudo_wash_json(numeric_id);
end;
$$;

create or replace function public.lavtudo_list_washes(p_user text, p_password text)
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  result jsonb;
begin
  if not private.lavtudo_admin_ok(p_user, p_password) then
    raise insufficient_privilege using message = 'Credenciais administrativas inválidas.';
  end if;

  select coalesce(jsonb_agg(private.lavtudo_wash_json(wash.id) order by wash.updated_at desc), '[]'::jsonb)
    into result
    from public.lavtudo_washes as wash;
  return result;
end;
$$;

create or replace function public.lavtudo_create_wash(
  p_user text,
  p_password text,
  p_customer_name text,
  p_machine_label text,
  p_service_type text,
  p_estimated_minutes integer
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  created_wash_id bigint;
begin
  if not private.lavtudo_admin_ok(p_user, p_password) then
    raise insufficient_privilege using message = 'Credenciais administrativas inválidas.';
  end if;

  insert into public.lavtudo_washes (
    customer_name, machine_label, service_type, estimated_minutes
  ) values (
    trim(p_customer_name), trim(p_machine_label), p_service_type, p_estimated_minutes
  ) returning id into created_wash_id;

  insert into public.lavtudo_wash_history (wash_id, status, label, actor)
  values (created_wash_id, 'waiting', private.lavtudo_status_label('waiting'), 'employee');

  return private.lavtudo_wash_json(created_wash_id);
end;
$$;

create or replace function public.lavtudo_set_wash_status(
  p_user text,
  p_password text,
  p_id text,
  p_status text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  target_wash_id bigint;
  previous_status text;
  changed_at timestamptz := now();
begin
  if not private.lavtudo_admin_ok(p_user, p_password) then
    raise insufficient_privilege using message = 'Credenciais administrativas inválidas.';
  end if;
  if p_id !~ '^[0-9]{1,12}$' then
    return null;
  end if;
  if p_status not in ('waiting', 'washing', 'rinsing', 'spinning', 'drying', 'ready', 'collected', 'cancelled') then
    raise check_violation using message = 'Status de lavagem inválido.';
  end if;

  target_wash_id := p_id::bigint;
  select status into previous_status
    from public.lavtudo_washes
    where id = target_wash_id
    for update;
  if not found then
    return null;
  end if;
  if previous_status = p_status then
    return private.lavtudo_wash_json(target_wash_id);
  end if;

  update public.lavtudo_washes
  set status = p_status,
      updated_at = changed_at,
      started_at = case
        when p_status = 'washing' and started_at is null then changed_at
        else started_at
      end,
      ready_at = case
        when p_status = 'ready' then changed_at
        when p_status not in ('ready', 'collected') then null
        else ready_at
      end
  where id = target_wash_id;

  insert into public.lavtudo_wash_history (wash_id, status, label, occurred_at, actor)
  values (target_wash_id, p_status, private.lavtudo_status_label(p_status), changed_at, 'employee');

  return private.lavtudo_wash_json(target_wash_id);
end;
$$;

create or replace function public.lavtudo_reset_wash(
  p_user text,
  p_password text,
  p_id text
)
returns jsonb
language plpgsql
volatile
security definer
set search_path = ''
as $$
declare
  target_wash_id bigint;
  changed_at timestamptz := now();
  history_actor text := 'employee';
begin
  if not private.lavtudo_admin_ok(p_user, p_password) then
    raise insufficient_privilege using message = 'Credenciais administrativas inválidas.';
  end if;
  if p_id !~ '^[0-9]{1,12}$' then
    return null;
  end if;
  target_wash_id := p_id::bigint;

  if target_wash_id = 1024 then
    insert into public.lavtudo_washes (
      id, customer_name, machine_label, service_type, status, estimated_minutes,
      created_at, updated_at, started_at, ready_at
    ) overriding system value values (
      1024, 'Cliente LavTudo', 'Lavadora 01', 'wash-dry', 'waiting', 45,
      changed_at, changed_at, null, null
    )
    on conflict (id) do update set
      customer_name = excluded.customer_name,
      machine_label = excluded.machine_label,
      service_type = excluded.service_type,
      status = excluded.status,
      estimated_minutes = excluded.estimated_minutes,
      created_at = excluded.created_at,
      updated_at = excluded.updated_at,
      started_at = null,
      ready_at = null;
    history_actor := 'system';
  else
    update public.lavtudo_washes
    set status = 'waiting', updated_at = changed_at, started_at = null, ready_at = null
    where id = target_wash_id;
    if not found then
      return null;
    end if;
  end if;

  delete from public.lavtudo_wash_history as history
  where history.wash_id = target_wash_id;
  insert into public.lavtudo_wash_history (wash_id, status, label, occurred_at, actor)
  values (target_wash_id, 'waiting', private.lavtudo_status_label('waiting'), changed_at, history_actor);

  return private.lavtudo_wash_json(target_wash_id);
end;
$$;

revoke all on function public.lavtudo_get_wash(text) from public, authenticated;
revoke all on function public.lavtudo_list_washes(text, text) from public, authenticated;
revoke all on function public.lavtudo_create_wash(text, text, text, text, text, integer) from public, authenticated;
revoke all on function public.lavtudo_set_wash_status(text, text, text, text) from public, authenticated;
revoke all on function public.lavtudo_reset_wash(text, text, text) from public, authenticated;

grant execute on function public.lavtudo_get_wash(text) to anon;
grant execute on function public.lavtudo_list_washes(text, text) to anon;
grant execute on function public.lavtudo_create_wash(text, text, text, text, text, integer) to anon;
grant execute on function public.lavtudo_set_wash_status(text, text, text, text) to anon;
grant execute on function public.lavtudo_reset_wash(text, text, text) to anon;

insert into public.lavtudo_washes (
  id, customer_name, machine_label, service_type, status, estimated_minutes
) overriding system value values (
  1024, 'Cliente LavTudo', 'Lavadora 01', 'wash-dry', 'waiting', 45
)
on conflict (id) do nothing;

insert into public.lavtudo_wash_history (wash_id, status, label, actor)
select 1024, 'waiting', private.lavtudo_status_label('waiting'), 'system'
where not exists (
  select 1 from public.lavtudo_wash_history where wash_id = 1024
);
